### ISSUE TITLE
AttributeError: 'str' object has no attribute 'phase' when using the "as_plays()" method

### ISSUE THREAD

**Issue by BlackArbsCEO** [BurntSushi/nfldb#122]
I'm using Windows 8.1, WinPython 2.7. 

I copied the example from the NFLDB intro page. 

```Python
q = nfldb.Query(db)
q.game(season_year=2012, season_type='Regular')
q.player(full_name='Tom Brady').play_player(passing_yds__ge=60)
for p in q.as_plays():
    print p
```
I get this error. 

```Python
Traceback (most recent call last):

  File "<ipython-input-2-21e7fc427f5e>", line 6, in <module>
    print p

  File "C:\Users\Owner\Downloads\Python_Installs\WinPython-64bit-2.7.6.4\python-2.7.6.amd64\lib\site-packages\nfldb\types.py", line 1748, in __str__
    % (self.pos_team, self.yardline, self.time.phase,

AttributeError: 'str' object has no attribute 'phase'
```

**Comment by nickcluc** [comment]
With OSX El Capitan, Python 2.7.10 I get:

```(NE, OWN 17, Q2, 1 and 10) (9:56) (Shotgun) T.Brady pass short left to S.Vereen for 83 yards, TOUCHDOWN.```
```(NE, OWN 37, Q3, 3 and 10) (10:00) (Shotgun) T.Brady pass deep middle to D.Stallworth for 63 yards, TOUCHDOWN. NE 12-Brady 18th career game with 4+ TD passes, passing Johnny Unitas for 4th most all-time.```

**Comment by BlackArbsCEO** [comment]
Not sure what the problem was. I updated to latest and final WinPython 2.7.10.3 version, updated my Psycopg2 install and it worked fine.

**Comment by BlackArbsCEO** [comment]
This error started popping up again. I'm really not sure what the cause could be...
