### ISSUE TITLE
Unicode error when updating

### ISSUE THREAD

**Issue by andr3w321** [BurntSushi/nfldb#140]
Anyone else getting this error or have any idea how to fix it?

```
$ nfldb-update 
-------------------------------------------------------------------------------
STARTING NFLDB UPDATE AT 2016-02-11 00:12:03.987734
Connecting to nfldb... done.
Setting timezone to UTC... done.
Locking write access to tables... done.
Updating season phase, year and week... done.
Bulk inserting data for 7 games...
	Sending batch of data to database.
Traceback (most recent call last):
  File "/home/jane/.local/bin/nfldb-update", line 39, in <module>
    nfldb.update.run(**vars(args))
  File "/home/jane/.local/lib/python2.7/site-packages/nfldb/update.py", line 535, in run
    doit()
  File "/home/jane/.local/lib/python2.7/site-packages/nfldb/update.py", line 525, in doit
    update_games(db, batch_size=batch_size)
  File "/home/jane/.local/lib/python2.7/site-packages/nfldb/update.py", line 397, in update_games
    bulk_insert_game_data(cursor, scheduled, batch_size=batch_size)
  File "/home/jane/.local/lib/python2.7/site-packages/nfldb/update.py", line 195, in bulk_insert_game_data
    do()
  File "/home/jane/.local/lib/python2.7/site-packages/nfldb/update.py", line 188, in do
    nfldb.db._big_insert(cursor, table, bulk[table])
  File "/home/jane/.local/lib/python2.7/site-packages/nfldb/db.py", line 353, in _big_insert
    values = ', '.join(_mogrify(cursor, times(vals(data))) for data in datas)
  File "/home/jane/.local/lib/python2.7/site-packages/nfldb/db.py", line 353, in <genexpr>
    values = ', '.join(_mogrify(cursor, times(vals(data))) for data in datas)
  File "/home/jane/.local/lib/python2.7/site-packages/nfldb/db.py", line 231, in _mogrify
    return cursor.mogrify('%s', (tuple(xs),))
  File "/home/jane/.local/lib/python2.7/site-packages/psycopg2/extensions.py", line 134, in getquoted
    qobjs = [o.getquoted() for o in pobjs]
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 20: ordinal not in range(128)
```

I have all the games schedules and scores but not the detailed play by play it looks like.
```
nfldb=> select gsis_id,week,away_team,home_team,away_score,home_score from game where season_year = 2015 and season_type = 'Postseason';
  gsis_id   | week | away_team | home_team | away_score | home_score 
------------+------+-----------+-----------+------------+------------
 2016010900 |    1 | KC        | HOU       |         30 |          0
 2016010901 |    1 | PIT       | CIN       |         18 |         16
 2016011000 |    1 | SEA       | MIN       |         10 |          9
 2016011001 |    1 | GB        | WAS       |         35 |         18
 2016011600 |    2 | KC        | NE        |         20 |         27
 2016011601 |    2 | GB        | ARI       |         20 |         26
 2016011700 |    2 | SEA       | CAR       |         24 |         31
 2016011701 |    2 | PIT       | DEN       |         16 |         23
 2016012400 |    3 | NE        | DEN       |         18 |         20
 2016012401 |    3 | ARI       | CAR       |         15 |         49
 2016020700 |    5 | CAR       | DEN       |         10 |         24


nfldb=> select * from drive where gsis_id = 2016011700::gameid;
 gsis_id | drive_id | start_field | start_time | end_field | end_time | pos_team | pos_time | first_downs | result | penalty_yards | yards_gained | play_count | time_inserted | time_updated 
---------+----------+-------------+------------+-----------+----------+----------+----------+-------------+--------+---------------+--------------+------------+---------------+--------------
```

**Comment by andr3w321** [comment]
Anyone have any ideas for how to fix this?  Maybe some of my gamecenter-json got corrupted?  I added some code to psycopg2/extension.py to see exactly where the error is occuring 

```
for i in pobjs:
    print i
```
and I get the following output running `nfldb-update`

```
<psycopg2.extensions.NoneAdapter object at 0x7ff967c8d690>
0
0
0
0
0
0
0
0
0
0
0
0
0
0
'NOW()'
'NOW()'
'2016011600'
19
4463
ROW('Q4', 868)::game_time
'NE'
ROW(13)::field_pos
3
13
'(:32) T.Brady kneels to KC 38 for -1 yards.'
<psycopg2.extensions.NoneAdapter object at 0x7ff967c8d690>
0
0
0
0
0
0
0
0
0
1
0
1
0
0
'NOW()'
'NOW()'
'2016011600'
19
4484
ROW('Final', 0)::game_time
'UNK'
NULL
<psycopg2.extensions.NoneAdapter object at 0x7ff967c8d690>
0
Traceback (most recent call last):
  File "/home/jane/.local/bin/nfldb-update", line 39, in <module>
    nfldb.update.run(**vars(args))
  File "/home/jane/.local/lib/python2.7/site-packages/nfldb/update.py", line 535, in run
    doit()
  File "/home/jane/.local/lib/python2.7/site-packages/nfldb/update.py", line 525, in doit
    update_games(db, batch_size=batch_size)
  File "/home/jane/.local/lib/python2.7/site-packages/nfldb/update.py", line 397, in update_games
    bulk_insert_game_data(cursor, scheduled, batch_size=batch_size)
  File "/home/jane/.local/lib/python2.7/site-packages/nfldb/update.py", line 195, in bulk_insert_game_data
    do()
  File "/home/jane/.local/lib/python2.7/site-packages/nfldb/update.py", line 188, in do
    nfldb.db._big_insert(cursor, table, bulk[table])
  File "/home/jane/.local/lib/python2.7/site-packages/nfldb/db.py", line 353, in _big_insert
    values = ', '.join(_mogrify(cursor, times(vals(data))) for data in datas)
  File "/home/jane/.local/lib/python2.7/site-packages/nfldb/db.py", line 353, in <genexpr>
    values = ', '.join(_mogrify(cursor, times(vals(data))) for data in datas)
  File "/home/jane/.local/lib/python2.7/site-packages/nfldb/db.py", line 231, in _mogrify
    return cursor.mogrify('%s', (tuple(xs),))
  File "/home/jane/.local/lib/python2.7/site-packages/psycopg2/extensions.py", line 135, in getquoted
    print i
```

I tried deleting all the 2016 gamecenter-json, but that did not seem to help.  If I pull the play by play from a different working nfldb for this game I get the following for the last 3 plays
```
  gsis_id   | drive_id | play_id |   time    | pos_team | yardline | down | yards_to_go |                                                                                                                                                  description                                                                                                                                                  |  note   |         time_inserted         |         time_updated          | first_down | fourth_down_att | fourth_down_conv | fourth_down_failed | passing_first_down | penalty | penalty_first_down | penalty_yds | rushing_first_down | third_down_att | third_down_conv | third_down_failed | timeout | xp_aborted 
------------+----------+---------+-----------+----------+----------+------+-------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+-------------------------------+-------------------------------+------------+-----------------+------------------+--------------------+--------------------+---------+--------------------+-------------+--------------------+----------------+-----------------+-------------------+---------+------------
 2016011600 |       19 |    4484 | (Final,0) | UNK      |          |      |           0 | END GAME NE-12 Brady’s 22nd career postseason win, extends his NFL record. Bill Belichick 23rd career postseason win, most by head coach in NFL history (Tom Landry, 20). Robert Kraft's 25th career postseason win, 3rd-most all-time by an owner.                                                           |         | 2016-01-28 15:01:16.407711-08 | 2016-01-28 15:01:16.407711-08 |          0 |               0 |                0 |                  0 |                  0 |       0 |                  0 |           0 |                  0 |              0 |               0 |                 0 |       0 |          0
 2016011600 |       19 |    4463 | (Q4,868)  | NE       | (13)     |    3 |          13 | (:32) T.Brady kneels to KC 38 for -1 yards.                                                                                                                                                                                                                                                                   |         | 2016-01-28 15:01:16.407711-08 | 2016-01-28 15:01:16.407711-08 |          0 |               0 |                0 |                  0 |                  0 |       0 |                  0 |           0 |                  0 |              1 |               0 |                 1 |       0 |          0
 2016011600 |       19 |    4442 | (Q4,841)  | NE       | (14)     |    2 |          12 | (:59) T.Brady kneels to KC 37 for -1 yards.
```
It seems to be failing on the strange end of game play description.

**Comment by andr3w321** [comment]
Fixed!  I had to manually delete the apostrophe from the json file in "Brady's" and it seems to work now.

```
gunzip 2016011600.json.gz
vim 2016011600.json
gzip 2016011600.json
```
