### ISSUE TITLE
Attribute error SQL

### ISSUE THREAD

**Issue by ealco9** [BurntSushi/nfldb#143]
I'm having trouble with the installation, everything's fine-ish up to the point when I'm supposed to run import nfldb in order to test it when I keep getting the following error:

File "/Library/Python/2.7/site-packages/nfldb/query.py", line 12, in <module>
    import nfldb.sql as sql
AttributeError: 'module' object has no attribute 'sql'

Does anyone know what can be causing it and how I could fix it?

Thanks!

**Comment by ochawkeye** [comment]
What version of `nfldb` do you have?

```bash
P:\>python -c "import nfldb; print nfldb.__version__"
0.2.14
```

**Comment by ealco9** [comment]
0.2.14 running on mac OSX

**Comment by ochawkeye** [comment]
What does your script look like that is importing nfldb?

**Comment by ealco9** [comment]
>>> import nfldb
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/nfldb/__init__.py", line 64, in <module>
    from nfldb.query import __pdoc__ as __query_pdoc__
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/nfldb/query.py", line 12, in <module>
    import nfldb.sql as sql
AttributeError: 'module' object has no attribute 'sql'

That's the entire traceback beginning with the command I'm attempting to run

**Comment by ochawkeye** [comment]
How did you install?  And where are you running this from?

There is a file `sql.py` that is supposed to be in your nfldb directory if installed properly.
![image](https://cloud.githubusercontent.com/assets/2996205/13438408/82bcae9c-dfae-11e5-9028-4b34d613af28.png)

**Comment by ealco9** [comment]
![screen shot 2016-03-01 at 1 10 11 pm](https://cloud.githubusercontent.com/assets/6990252/13438516/fa1aef76-dfae-11e5-853c-2a750a83ae78.png)

It's there, I installed it using pip but for some reason it's not picking it up.

**Comment by ealco9** [comment]
It's there, I installed using pip but for some reason it's not picking it up

![screen shot 2016-03-01 at 1 10 11 pm](https://cloud.githubusercontent.com/assets/6990252/13438616/5c47b12a-dfaf-11e5-94a1-ff53d98b1a4b.png)

**Comment by ealco9** [comment]
It's there, I installed using pip but for some reason it's not picking it up

**Comment by ealco9** [comment]
Also i'm running it using PyCharm's django console

**Comment by ealco9** [comment]
I'm still having this issue, I installed nfldb on my mac using sudo pip install --user nfldb and no errors, I can run nflgame without issue but when i run >>> import nfldb I get AttributeError: 'module' object has no attribute 'sql' even though the files do seem to be installed.

Also when I try to upgrade every time it says "requirement already satisfied".

Any thoughts?
