### ISSUE TITLE
Issues After Update

### ISSUE THREAD

**Issue by donlaur** [BurntSushi/nfldb#185]
Not sure if I did this wrong but I had the nfldb-update command working without errors after doing the fixes.

Then I did the command today of 
pip install nfldb --upgrade
and it worked.

This one did not work.
nfldb-update --update-schedules

Then I run nfldb-update and I get the following.
STARTING NFLDB UPDATE AT 2016-09-08 20:57:29.613564
Connecting to nfldb... Traceback (most recent call last):
  File "/usr/bin/nfldb-update", line 39, in <module>
    nfldb.update.run(**vars(args))
  File "/usr/lib/python2.7/site-packages/nfldb/update.py", line 535, in run
    doit()
  File "/usr/lib/python2.7/site-packages/nfldb/update.py", line 502, in doit
    db = nfldb.connect()
  File "/usr/lib/python2.7/site-packages/nfldb/db.py", line 137, in connect
    _migrate(conn, api_version)
  File "/usr/lib/python2.7/site-packages/nfldb/db.py", line 447, in _migrate
    globs[fname](c)
  File "/usr/lib/python2.7/site-packages/nfldb/db.py", line 911, in _migrate_8
    ''' % (', '.join(_mogrify(c, team[0:3]) for team in nfldb.team.teams2)))
  File "/usr/lib64/python2.7/site-packages/psycopg2/extras.py", line 223, in execute
    return super(RealDictCursor, self).execute(query, vars)
psycopg2.IntegrityError: duplicate key value violates unique constraint "team_pkey"
DETAIL:  Key (team_id)=(LA) already exists.

**Comment by BurntSushi** [comment]
Did you modify your database at all? e.g. By inserting a row into the `team` table?

I'd recommend [downloading the SQL dump again](http://burntsushi.net/stuff/nfldb/nfldb.sql.zip) and starting fresh. I updated it today, so you won't need to rebuild the preseason.

**Comment by donlaur** [comment]
Yes, removing the LA entry in the DB fixed it.  Sorry.
