### ISSUE TITLE
ValueError: Extra data

### ISSUE THREAD

**Issue by danielcroona** [BurntSushi/nfldb#187]
Hi!

When running the update script during todays games I keep getting this error. Tried to update all python packages with pip but that made no difference. Is there anyone else getting this?

$ sudo nfldb-update
Traceback (most recent call last):
  File "/usr/local/bin/nfldb-update", line 5, in <module>
    import nfldb.update
  File "/usr/local/lib/python2.7/dist-packages/nfldb/update.py", line 15, in <module>
    import nflgame
  File "/usr/local/lib/python2.7/dist-packages/nflgame/__init__.py", line 114, in <module>
    players = nflgame.player._create_players()
  File "/usr/local/lib/python2.7/dist-packages/nflgame/player.py", line 21, in _create_players
    data = json.loads(open(jsonf).read())
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 369, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 111228 column 8 - line 111238 column 2 (char 3415175 - 3415465)

**Comment by danielcroona** [comment]
Apparently I did not update nfldb properly. I am closing this issue.

**Comment by BurntSushi** [comment]
@danielcroona What did you do to fix it?

**Comment by danielcroona** [comment]
I just upgraded nfldb, and then I had to remove my entry for the LA Rams from the team database that I had made previously.

The update command:
`sudo pip install nfldb --upgrade`
