### ISSUE TITLE
nfldb stopped updating

### ISSUE THREAD

**Issue by mrg1999** [BurntSushi/nfldb#195]
My scores stopped updating around half-time on Sunday of week 2. All the late games have no scores and none of the games (except for Thursday's game) show as 'finished'.
I tried running  nfldb-update directly from a shell script but nothing changed:

STARTING NFLDB UPDATE AT 2016-09-19 18:16:56.970000
Connecting to nfldb... done.
Setting timezone to UTC... done.
Locking write access to tables... done.
Updating season phase, year and week... done.
Bulk inserting data for 7 games...
        Sending batch of data to database.
        Sending batch of data to database.
Traceback (most recent call last):
  File "nfldb-update", line 39, in <module>
    nfldb.update.run(**vars(args))
  File "C:\Python27\lib\site-packages\nfldb\update.py", line 535, in run
    doit()
  File "C:\Python27\lib\site-packages\nfldb\update.py", line 525, in doit
    update_games(db, batch_size=batch_size)
  File "C:\Python27\lib\site-packages\nfldb\update.py", line 397, in update_games
    bulk_insert_game_data(cursor, scheduled, batch_size=batch_size)
  File "C:\Python27\lib\site-packages\nfldb\update.py", line 221, in bulk_insert_game_data
    do()
  File "C:\Python27\lib\site-packages\nfldb\update.py", line 188, in do
    nfldb.db._big_insert(cursor, table, bulk[table])
  File "C:\Python27\lib\site-packages\nfldb\db.py", line 356, in _big_insert
    % (table, insert_fields, values))
  File "C:\Python27\lib\site-packages\psycopg2\extras.py", line 223, in execute
    return super(RealDictCursor, self).execute(query, vars)
psycopg2.IntegrityError: insert or update on table "play" violates foreign key constraint "play_pos_team_fkey"
DETAIL:  Key (pos_team)=(JAX) is not present in table "team".

**Comment by mrg1999** [comment]
Looks like this is already being addressed in #194
