### ISSUE TITLE
when run  nfldb-update get a KeyError.

### ISSUE THREAD

**Issue by JulianZhang** [BurntSushi/nfldb#196]
I had create a new database as http://burntsushi.net/stuff/nfldb/nfldb.sql.zip .
But I can't run update, each time will get error as blow.

./nfldb-update
-------------------------------------------------------------------------------
STARTING NFLDB UPDATE AT 2016-09-20 00:13:27.361961
Connecting to nfldb... done.
Setting timezone to UTC... done.
Locking write access to tables... done.
Updating season phase, year and week... http://www.nfl.com/liveupdate/scorestrip/ss.xml
done.
Adding schedule data for 6 games... done.
Bulk inserting data for 39 games...
	Sending batch of data to database.
Traceback (most recent call last):
  File "./nfldb-update", line 39, in <module>
    nfldb.update.run(**vars(args))
  File "/opt/projects/futulefo/nfldb/update.py", line 535, in run
    doit()
  File "/opt/projects/futulefo/nfldb/update.py", line 525, in doit
    update_games(db, batch_size=batch_size)
  File "/opt/projects/futulefo/nfldb/update.py", line 397, in update_games
    bulk_insert_game_data(cursor, scheduled, batch_size=batch_size)
  File "/opt/projects/futulefo/nfldb/update.py", line 197, in bulk_insert_game_data
    g = game_from_id(cursor, gsis_id)
  File "/opt/projects/futulefo/nfldb/update.py", line 54, in game_from_id
    schedule = nflgame.sched.games[gsis_id]
KeyError: '2016080751'

**Comment by BurntSushi** [comment]
Please make sure you're running the latest version of both `nflgame` and `nfldb`.

**Comment by JulianZhang** [comment]
THANK YOU, the problem is version mismatch.

**Comment by JulianZhang** [comment]
THANK YOU, the problem is version mismatch.

**Comment by JulianZhang** [comment]
THANK YOU, the problem is version mismatch.

**Comment by reesmichael1** [comment]
@BurntSushi Apologies for bringing up a closed issue, but I'm encountering the exact same error.

```
$ nfldb-update 
-------------------------------------------------------------------------------
STARTING NFLDB UPDATE AT 2016-11-02 14:52:46.028628
Connecting to nfldb... done.
Setting timezone to UTC... done.
Locking write access to tables... done.
Updating season phase, year and week... done.
Bulk inserting data for 121 games...
Traceback (most recent call last):
  File "/usr/bin/nfldb-update", line 39, in <module>
    nfldb.update.run(**vars(args))
  File "/usr/lib/python2.7/site-packages/nfldb/update.py", line 535, in run
    doit()
  File "/usr/lib/python2.7/site-packages/nfldb/update.py", line 525, in doit
    update_games(db, batch_size=batch_size)
  File "/usr/lib/python2.7/site-packages/nfldb/update.py", line 397, in update_games
    bulk_insert_game_data(cursor, scheduled, batch_size=batch_size)
  File "/usr/lib/python2.7/site-packages/nfldb/update.py", line 197, in bulk_insert_game_data
    g = game_from_id(cursor, gsis_id)
  File "/usr/lib/python2.7/site-packages/nfldb/update.py", line 54, in game_from_id
    schedule = nflgame.sched.games[gsis_id]
KeyError: '2016080751'
```

In my case, I seem to be running the most recent version of both nfldb and nflgame:

```
$ pip2 freeze | grep -E "nfldb|nflgame"
nfldb==0.2.17
nflgame==1.2.20
```

Do you have any ideas on what I should do? It may very well be important to note that I previously had a working installation of nfldb which broke with a postgresql update, so I attempted to rebuild the database by deleting /var/lib/postgres and following the Installation page of the wiki again.

In case it's useful, this is occurring on an up-to-date Arch Linux system. Just in case, I've reinstalled both nfldb and nflgame.
