### ISSUE TITLE
Player Name Error 

### ISSUE THREAD

**Issue by iamboom** [BurntSushi/nfldb#214]
It has to do with the extra "," in the name. Does anyone know a good way to work around that per chance?

Could not get player info from roster row:

<tr class="even">
<td>72</td>
<td style="text-align:left"> <a href="/player/charleslenojr./2550169/profile">Leno, Charles, Jr.</a></td>
<td>T</td>
<td>ACT</td>
<td> 6'3"</td>
<td>305</td>
<td>10/9/1991</td>
<td>3</td>
<td>Boise State</td></tr>

Exception:

Traceback (most recent call last):
  File "C:\Anaconda2\lib\site-packages\nflgame\update_players.py", line 419, in run
    roster.append(meta_from_soup_row(team, row))
  File "C:\Anaconda2\lib\site-packages\nflgame\update_players.py", line 179, in meta_from_soup_row
    last_name, first_name = map(lambda s: s.strip(), name.split(','))
ValueError: too many values to unpack

**Comment by snake-plissken** [comment]
The split function needs the second parameter to indicate how many times to split, and in this case we only want one split:

`last_name, first_name = map(lambda s: s.strip(), name.split(',', 1))`

Technically, it's an issue with https://github.com/BurntSushi/nflgame/

I'm actually kind of surprised this hasn't been an issue yet.  I thought there were a few players with the Jr suffix (i.e. Duke Johnson Jr, Ted Ginn Jr).  Turns out it's how they are listed at http://www.nfl.com/players/profile, and that name does not always match what is on the back of their jerseys.  Right now it looks like Charles Leno Jr is the only active player in the NFL, officially, with a Jr suffix in his name.  Also, he's been playing since 2014, so did he just change his name?

**Comment by nokemono42** [comment]
@snake-plissken You should probably make a pull request for that fix. It worked for me.

**Comment by GarageVIEW** [comment]
@nokemono42 Sorry I'm new to GitHub.
I see someone issued a pull request for the fix. How do I get that branch?
