### ISSUE TITLE
nfldb Mac installation

### ISSUE THREAD

**Issue by cminton** [BurntSushi/nfldb#215]
Has anyone installed nfldb on the mac? I have installed postgres and pgAdmin. I am at the point where I create the actual postgresql db. The following command is not recognized:

systemd-tmpfiles --create postgresql.conf

**Comment by BurntSushi** [comment]
Systemd is a Linux init system. It wouldn't be available on a Mac.

**Comment by cminton** [comment]
Thanks Andrew. I am trying to set up nfldb, so I can move to it. I am excellent at application development, but very out of touch with systems, so not so good at this type of set up. Does anyone know what steps I take from this point to be able to use nfldb on a Mac?

**Comment by BurntSushi** [comment]
It sounds like you need to find a generic tutorial for setting up postgres
on a mac. You'll probably also want to look up how to install the psycopg2
python module for mac.

**Comment by AndrewRook** [comment]
@cminton I wrote up the steps I had to go through to get nfldb working on my Mac [here](http://nflwin.readthedocs.io/en/stable/nfldb.html). It's mostly written so I wouldn't forget how to do it myself, but it might have some useful tips.

**Comment by cminton** [comment]
@AndrewRook thank you. When I get to 

postgres -D /usr/local/var/postgres

It just seems to hang there. Is it waiting for something from me?

**Comment by AndrewRook** [comment]
Yeah, that's normal - that command is running the database in the foreground (the `pg_ctl -D /usr/local/var/postgres -l logfile start` command right below it is to run the db in the background, although I prefer running postgres in the foreground so I can kill it easily). 

If you decide you're happy running postgres in the foreground (ctrl-c should kill it if you want to try the background command) you'll need to open up a new terminal window (command+n) or tab (command+t) and continue there.

**Comment by cminton** [comment]
I figured it was looping. I should have thought of opening another terminal window. That was dumb of me.

**Comment by cminton** [comment]
Any idea what this error is? I am superuser, so do not think it is permissioning...

Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Python/2.7/site-packages/pip/wheel.py", line 377, in move_wheel_files
    clobber(source, dest, False, fixer=fixer, filter=filter)
  File "/Library/Python/2.7/site-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/Library/Python/2.7/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 1] Operation not permitted: '/System/Library/Frameworks/Python.framework/Versions/2.7/share'

**Comment by cminton** [comment]
I got that error running

pip2 install nfldb

**Comment by AndrewRook** [comment]
[Looks like this is a security feature in El Cap](http://stackoverflow.com/questions/33004708/osx-el-capitan-sudo-pip-install-oserror-errno-1-operation-not-permitted). The simple answer (as recommended in that SO question) is to use a virtual environment. The SO answer recommends `virtualenv` which is a perfectly fine choice, but personally I recommend [Miniconda](http://conda.pydata.org/docs/install/quick.html), which will make it way easier if you want to either run multiple versions of Python simultaneously or use libraries like numpy or scipy.

**Comment by cminton** [comment]
Then I use a virtual environment to continue the installation or every time I use nfldb?

**Comment by AndrewRook** [comment]
Both, basically. You'll install nfldb (and any other packages you need) into the virtual environment, and then whenever you want to use nfldb you'll activate the virtual environment and work from there. Personally I use a new virtual environment for every project - that way you never have to worry about dependencies conflicting between projects.

One caveat, however - the nfldb database **will** be visible across virtual environments, which is actually kind of nice - if you use nfldb in multiple projects you shouldn't have to remake the database for each one.

**Comment by Arrashg** [comment]
Hey all,

complete noob here just getting into python and sql. I have attempted to install and had to uninstall, erase my mac a once already. Anyways, when I try these commands, this is what I get:

<img width="511" alt="screen shot 2017-08-18 at 9 11 57 pm" src="https://user-images.githubusercontent.com/20796673/29483385-07785ba8-845a-11e7-96e5-ab4a43cdee95.png">

Thanks for the help!

**Comment by Arrashg** [comment]
Hey all, getting stuck at this part of this guide:

http://nflwin.readthedocs.io/en/stable/nfldb.html

<img width="520" alt="screen shot 2017-08-18 at 9 48 26 pm" src="https://user-images.githubusercontent.com/20796673/29483622-29f9d6b6-845f-11e7-9631-c2592461fbca.png">

**Comment by Arrashg** [comment]
Ok and then I got to here

<img width="525" alt="screen shot 2017-08-18 at 9 54 13 pm" src="https://user-images.githubusercontent.com/20796673/29483656-da2c9c58-845f-11e7-9066-5b5777936714.png">

**Comment by cminton** [comment]
I can't get the NFL db to work either. However, I have a lot of code to pull stats using the API.

Charlie

**Comment by Arrashg** [comment]
@cminton can you help me do that? or are there instructions anywhere for how to do that?

**Comment by cminton** [comment]
Happy to. I am on a trip, but back Sunday. What data are you looking for?

**Comment by Arrashg** [comment]
@cminton Not sure 100% what the etiquette is so I won't post links but I have a site full of NFL teams, schedule, games played and player profiles I need to populate with standard data such as catches, yards, etc after every game. 

What I would also like is targets, red zone targets, yards after contact, aDOT on top of that. Goal is to build a daily fantasy stacking tool and eventually a game center that updates.

**Comment by cminton** [comment]
@Arrashg I have Python code to pull all of that data. What is "aDOT"?

Others who use nflgame say that the db is a much better way to go, so it may be worth your time to get that to work. That said, happy to give you my code.

Charlie

**Comment by Arrashg** [comment]
@cminton Average Depth of Target for receivers. 

Ok thank you. I'll utilize your code and also keep trying to get the DB up and running at the same time.

**Comment by cminton** [comment]
@Arrashg,

Just landed. Give me a few hours. I have the code for that.

Charlie

**Comment by AndrewRook** [comment]
Hey @Arrashg, going back to [this comment](https://github.com/BurntSushi/nfldb/issues/215#issuecomment-323500366), is your username "home"? If that's the case, it looks like you may have missed the step directly after starting up postgres for the first time:

```bash
$ createdb `whoami`
```

That will create a database based on your username, which should solve the does not exist error you got.

**Comment by Arrashg** [comment]
@AndrewRook Thank you! That worked but How do I get out of here? I tried to set a password but then missed the rest of the command and now I'm stuck.

<img width="464" alt="screen shot 2017-08-20 at 7 39 31 pm" src="https://user-images.githubusercontent.com/20796673/29501725-9a762954-85df-11e7-8e61-23f785c5c406.png">

**Comment by Arrashg** [comment]
@AndrewRook Thanks a lot. Made a lot of progress and now I am at the final step of which I am confused about regarding "default configuration directory. I moved it to "Application Support" but not sure this is the correct place. I am an OSX newbie. When I added my password and saved the file, I tried the last few instructions but ended up with this:

<img width="1440" alt="screen shot 2017-08-20 at 10 11 12 pm" src="https://user-images.githubusercontent.com/20796673/29504473-d4af327c-85f4-11e7-9196-80f64f5fea55.png">

This is the section I am confused about:

<img width="725" alt="screen shot 2017-08-20 at 10 12 02 pm" src="https://user-images.githubusercontent.com/20796673/29504478-ddd65f2e-85f4-11e7-88f3-e8dc4b90c6fb.png">

**Comment by donlaur** [comment]
Download the default config.ini.sample file.
https://github.com/BurntSushi/nfldb/blob/master/config.ini.sample

Edit your details.  Save to one of those paths that it stated that it is
looking for the config file at such as
/Users/home/.config/nfldb/config.ini

**Comment by Arrashg** [comment]
I'm starting to think that nfldb was saved to the wrong folder. When I try and run it, it says no module named nfldb. I'm still unsure of which .config file to save it to. I tried moving it to .config and then to run it and I get the same problem. I have attached images of where I currently tried to add it.

I'm so close thanks to everyone's help.

<img width="838" alt="screen shot 2017-08-21 at 4 06 57 pm" src="https://user-images.githubusercontent.com/20796673/29541792-3b49c56a-868b-11e7-8267-0653575e8228.png">

<img width="1054" alt="screen shot 2017-08-21 at 4 07 42 pm" src="https://user-images.githubusercontent.com/20796673/29541794-41c50814-868b-11e7-98ef-db6c35637b71.png">

**Comment by AndrewRook** [comment]
@Arrashg if you're getting an `ImportError` when you try to import nfldb you probably have problems with how you installed the module itself, beyond just the config file. How did you install nfldb?

**Comment by Arrashg** [comment]
@AndrewRook I followed these steps
http://nflwin.readthedocs.io/en/stable/nfldb.html
After that, I moved on to these
https://github.com/BurntSushi/nfldb/wiki/Installation#importing-the-nfldb-database
It seemed like that all worked as I'm able to connect to nfldb.

<img width="453" alt="screen shot 2017-08-21 at 9 50 22 pm" src="https://user-images.githubusercontent.com/20796673/29549108-f2e81e4a-86ba-11e7-99af-ac9cbf15ad96.png">

I also tried what was suggested and the list of relations show up fine

<img width="378" alt="screen shot 2017-08-21 at 9 52 37 pm" src="https://user-images.githubusercontent.com/20796673/29549149-2aef8166-86bb-11e7-9bbf-a514de4e993d.png">

I did not notice any errors during install.

**Comment by ochawkeye** [comment]
None of the steps in the directions on http://nflwin.readthedocs.io explicitly has you install the python `nfldb` library.  Looks to me like you've got the Postgres database imported, but not the Python `nfldb` package.  

Try `pip install nfldb`.

**Comment by donlaur** [comment]
On the mac I had a better time with

sudo pip install --user nfldb

**Comment by Arrashg** [comment]
@ochawkeye Getting close here. Now when I run the command "import nfldb" it says command not found. When I run "nfldb-update" it updates the db!

<img width="1002" alt="screen shot 2017-08-25 at 9 00 16 pm" src="https://user-images.githubusercontent.com/20796673/29738498-8657301a-89d8-11e7-8463-1fb8de1adb2f.png">

**Comment by AndrewRook** [comment]
In order to use the nfldb Python package (which provides the API wrapper around the postgres database) you have to be running python, either as a script (e.g. `python script.py`) or through the command line interpreter:

```
$ python
<Python version information, your info may vary>
>>> import nfldb
```

**Comment by Arrashg** [comment]
@AndrewRook When I start python and >>> import nfldb, I get an ImportError but nfldb is located here so not sure why that is
/usr/local/lib/python2.7/site-packages/nfldb

<img width="579" alt="screen shot 2017-08-26 at 2 59 58 pm" src="https://user-images.githubusercontent.com/20796673/29745446-850228e0-8a6f-11e7-9c12-bbe7c9fee7b0.png">

<img width="755" alt="screen shot 2017-08-26 at 3 02 18 pm" src="https://user-images.githubusercontent.com/20796673/29745450-93fde280-8a6f-11e7-8a18-6b44f51ab0ec.png">

**Comment by AndrewRook** [comment]
that probably means that `/usr/local/lib/python2.7/site-packages/` isn't on any of the paths that python is searching when it figures out what packages are installed. This can happen for a few reasons, usually because the python installation you're actually using is different than the python installation you _think_ you're using.

You can see what paths your install is looking in by doing the following:

```
$ python
>>> import sys
>>> print(sys.path)
```
For more info on how python finds packages see [here](https://leemendelowitz.github.io/blog/how-does-python-find-packages.html). 

If this does turn out to be the problem you can either monkey around with `sys.path` (or the `PYTHONPATH` environment variable) or you can start using Python inside of virtual environments - I recommend [conda](https://conda.io/docs/user-guide/getting-started.html).
