### ISSUE TITLE
nfldb-update not working, Multiple errors

### ISSUE THREAD

**Issue by theSanchize3** [BurntSushi/nfldb#216]
I ran `nfldb-update` and got multiple errors. It's not allowing me to copy the output, but these were the errors I received:
1. `Could not get profile URL for (00-0032820, T.Smith)`
2. `Could not get player info from roster row:
`3. ```
Traceback (most recent call last):
    File "C:\Python2\lib\site-package\nflgame\update_players.py", line 419, in r
un
        roster.append(meta_from_soup_row(team, row))
    File "C:\Python27\lib\site-packages\nflgame\update_players.py", line 179, in m
eta_from_soup_row
        last_name, first_name = map(lamba s: s.strip(), name.split(','))
ValueError: too many values to unpack

```4. ```
psycopg2.IntegrityError: insert or update on table "play" violates foreign key c
constraint "play_pos_team_fkey"

```5. `DETAIL: Key (pos_team)=(JAX) is not present in table "team".`

I upgraded nfldb and nflgame but that did not work. I saw online someone suggested (to a different post) to user `python nfldb-update --play-interval 0`, but that did not work either.

Thanks in advance,
Sanchez

**Comment by andr3w321** [comment]
These are both known and open issues.  The most critical one is 194 which after you apply the hack should update just fine skipping over the player with multiple names.
https://github.com/BurntSushi/nfldb/issues/194
https://github.com/BurntSushi/nfldb/issues/214
