### ISSUE TITLE
Error doing nfldb-update

### ISSUE THREAD

**Issue by mesee298** [BurntSushi/nfldb#226]
Get the following when attempting to do a nfldb-update (with no parameters) for the FIRST TIME:
`
STARTING NFLDB UPDATE AT 2017-02-10 22:54:17.271172
Connecting to nfldb... done.
Setting timezone to UTC... done.
Locking write access to tables... done.
Updating season phase, year and week... done.
Bulk inserting data for 257 games...
        Sending batch of data to database.
Traceback (most recent call last):
  File "/usr/local/bin/nfldb-update", line 39, in <module>
    nfldb.update.run(**vars(args))
  File "/usr/local/lib/python2.7/dist-packages/nfldb/update.py", line 535, in run
    doit()
  File "/usr/local/lib/python2.7/dist-packages/nfldb/update.py", line 525, in doit
    update_games(db, batch_size=batch_size)
  File "/usr/local/lib/python2.7/dist-packages/nfldb/update.py", line 414, in update_games
    update_current_week_schedule(db)
  File "/usr/local/lib/python2.7/dist-packages/nfldb/db.py", line 320, in __exit__
    self.__conn.rollback()
psycopg2.InterfaceError: connection already closed
`

I've tried to do a `nfldb-update --batch-size 20` and get the above error.

If I try `nfldb-update --batch-size 21` then I get:
`
STARTING NFLDB UPDATE AT 2017-02-11 20:21:48.919588
Connecting to nfldb... done.
Setting timezone to UTC... done.
Locking write access to tables... done.
Updating season phase, year and week... done.
Bulk inserting data for 257 games...
        Sending batch of data to database.
Killed
`

**Comment by mesee298** [comment]
Okay, so I might have screwed it up even worse.  I dropped the db and rebuilt it.  Now I get the following:

`Traceback (most recent call last):
  File "/usr/local/bin/nfldb-update", line 5, in <module>
    import nfldb.update
  File "/usr/local/lib/python2.7/dist-packages/nfldb/update.py", line 15, in <module>
    import nflgame
  File "/usr/local/lib/python2.7/dist-packages/nflgame/__init__.py", line 114, in <module>
    players = nflgame.player._create_players()
  File "/usr/local/lib/python2.7/dist-packages/nflgame/player.py", line 21, in _create_players
    data = json.loads(open(jsonf).read())
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
`

**Comment by mesee298** [comment]
I figured it out on my own...

The server I was using was only 512mb RAM.  Increased to 1GB RAM and that fixed the problem.
