### ISSUE TITLE
nfldb-update simulate

### ISSUE THREAD

**Issue by mrg1999** [BurntSushi/nfldb#228]
Can someone please explain the proper format to use  `nfldb-update --simulate`
Thanks!

**Comment by mrg1999** [comment]
From what I can find it looks like it should be:
`nfldb-update --simulate 2017010106` 
But I get the following error:

```
Traceback (most recent call last):
  File "nfldb-update", line 38, in <module>
    nfldb.update.run(**vars(args))
  File "C:\Python27\lib\site-packages\nfldb\update.py", line 460, in run
    games = sorted(q.as_games(), key=lambda g: g.gsis_id)
  File "C:\Python27\lib\site-packages\nfldb\query.py", line 793, in as_games
    q = self._make_join_query(cursor, types.Game)
  File "C:\Python27\lib\site-packages\nfldb\query.py", line 762, in _make_join_query
    'where': sql.ands(self._sql_where(cursor)),
  File "C:\Python27\lib\site-packages\nfldb\query.py", line 1031, in _sql_where
    aliases=aliases, aggregate=aggregate)
  File "C:\Python27\lib\site-packages\nfldb\query.py", line 292, in _disjunctions
    ds.append(' AND '.join('(%s)' % sql(c) for c in conjuncts))
  File "C:\Python27\lib\site-packages\nfldb\query.py", line 292, in <genexpr>
    ds.append(' AND '.join('(%s)' % sql(c) for c in conjuncts))
  File "C:\Python27\lib\site-packages\nfldb\query.py", line 289, in sql
    return c._sql_where(cursor, aliases=aliases, aggregate=aggregate)
  File "C:\Python27\lib\site-packages\nfldb\query.py", line 352, in _sql_where
    'Disjunctions must use "=" for column "%s"' % field
AssertionError: Disjunctions must use "=" for column "game.gsis_id"
```

**Comment by farazirfan47** [comment]
Did you solve that problem ?
