### ISSUE TITLE
ValueError: Extra data:

### ISSUE THREAD

**Issue by danielcroona** [BurntSushi/nfldb#236]
I checked on on the regular nfldb-updates that is running on my server and apparently there are errors now that I can not understand how to solve. Does anyone know how to solve this?

> $ sudo /usr/local/bin/nfldb-update
> Traceback (most recent call last):
>   File "/usr/local/bin/nfldb-update", line 5, in <module>
>     import nfldb.update
>   File "/usr/local/lib/python2.7/dist-packages/nfldb/update.py", line 15, in <module>
>     import nflgame
>   File "/usr/local/lib/python2.7/dist-packages/nflgame/__init__.py", line 114, in <module>
>     players = nflgame.player._create_players()
>   File "/usr/local/lib/python2.7/dist-packages/nflgame/player.py", line 21, in _create_players
>     data = json.loads(open(jsonf).read())
>   File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
>     return _default_decoder.decode(s)
>   File "/usr/lib/python2.7/json/decoder.py", line 369, in decode
>     raise ValueError(errmsg("Extra data", s, end, len(s)))
> ValueError: Extra data: line 108441 column 2 - line 108441 column 3 (char 3322269 - 3322270)

**Comment by danielcroona** [comment]
I searched and found that I have been experiencing the exact same thing before. Sorry about the duplicate post.
