### ISSUE TITLE
ValueError: Extra data: line 116196 column 5 - line 116197 column 2 (char 3554115 - 3554118)

### ISSUE THREAD

**Issue by pla1** [BurntSushi/nfldb#251]
Hi, 

I am getting `ValueError: Extra data: line 116196 column 5 - line 116197 column 2 (char 3554115 - 3554118)` when running nfldb-update. I thought it was related to me monkeying around with the 'JAX' team-id issue. So, I dropped the nfldb database, re-created it, and imported the data from the nfldb.sql file. Still getting this `Extra data` error. Any suggestions on how to overcome this error? 

Thanks, PLA

root@ub-pla-nj01:/tmp# nfldb-update
Traceback (most recent call last):
  File "/usr/local/bin/nfldb-update", line 5, in <module>
    import nfldb.update
  File "/usr/local/lib/python2.7/dist-packages/nfldb/update.py", line 15, in <module>
    import nflgame
  File "/usr/local/lib/python2.7/dist-packages/nflgame/__init__.py", line 114, in <module>
    players = nflgame.player._create_players()
  File "/usr/local/lib/python2.7/dist-packages/nflgame/player.py", line 21, in _create_players
    data = json.loads(open(jsonf).read())
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 369, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 116196 column 5 - line 116197 column 2 (char 3554115 - 3554118)

**Comment by kennystruble** [comment]
were you able to resolve this?  I have the same issue...

**Comment by pla1** [comment]
@kennystruble Nope. I'm out of ideas.

**Comment by pla1** [comment]
@kennystruble Was your installation new? I am considering trying a fresh installation but not if I know it will result with this same error. Thanks.

**Comment by kennystruble** [comment]
no, i've had it since last season. I am about to attempt that. ill let you know how it goes.

**Comment by ochawkeye** [comment]
Rerunning `nfldb-update` still produces this error for both of you?  I just ran that this afternoon without issue.

Is there an invalid character of some sort currently living in your `players.json` file?  Here is my file as of a few minutes ago: [`players.json'](https://github.com/ochawkeye/nflgame/blob/master/nflgame/players.json)

It will replace your `lib/site-packages/nflgame/players.json` file.

**Comment by kennystruble** [comment]
@pla1 uninstalling and reinstalling nflgame and nfldb has seemed to fix the issue for me.

**Comment by pla1** [comment]
Congrats @kennystruble . I may be headed in that direction. 

Nice call @ochawkeye ! My players.json had two extra brackets at the end. I removed the extra two brackets and nfldb-update ran once but with errors. Looks like schedule.json is trashed too. nfldb-update is failing now with a different error now (see after screenshots). 

So, is there a way to download the two json files and recover? What do y'all think. Uninstall and re-install? 

![Imgur](http://i.imgur.com/WLTi2eO.png)

![Imgur](http://i.imgur.com/eMOdWfq.png)

nfldb-update 
Traceback (most recent call last):
  File "/usr/local/bin/nfldb-update", line 5, in <module>
    import nfldb.update
  File "/usr/local/lib/python2.7/dist-packages/nfldb/update.py", line 15, in <module>
    import nflgame
  File "/usr/local/lib/python2.7/dist-packages/nflgame/__init__.py", line 97, in <module>
    import nflgame.game  # noqa
  File "/usr/local/lib/python2.7/dist-packages/nflgame/game.py", line 12, in <module>
    import nflgame.sched
  File "/usr/local/lib/python2.7/dist-packages/nflgame/sched.py", line 47, in <module>
    games, last_updated = _create_schedule()
  File "/usr/local/lib/python2.7/dist-packages/nflgame/sched.py", line 26, in _create_schedule
    data = json.loads(open(jsonf).read())
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 45955 column 1 (char 738676)

**Comment by pla1** [comment]
Downloaded the json files from here: 

https://raw.githubusercontent.com/BurntSushi/nflgame/master/nflgame/players.json
https://raw.githubusercontent.com/BurntSushi/nflgame/master/nflgame/schedule.json

nfldb-update runs successfully now.

My [web app](http://nfl.pla1.net) is building up-to-date images now but I have to deal with the Chargers issue now.

Thanks @ochawkeye and @kennystruble !

![NFL image](http://xbmc-rocks.com/images/NFL201701Preseason.png?epoch=1503145027245)
