### ISSUE TITLE
KeyError on Update

### ISSUE THREAD

**Issue by etsweeney** [BurntSushi/nfldb#264]
Hey all,

Apologies if this has been brought up before - did a search and couldn't find anything though.

I've got an NFLDB Postgres instance running on Amazon RDS and the update script running on an EC2 instance. This weekend, it started failing with this error:

> STARTING NFLDB UPDATE AT 2017-09-12 21:39:03.286000
> Connecting to nfldb... done.
> Setting timezone to UTC... done.
> Locking write access to tables... done.
> Updating season phase, year and week... done.
> Bulk inserting data for 3 games...
> Traceback (most recent call last):
>   File "c:\python27\scripts\nfldb-update", line 39, in <module>
>     nfldb.update.run(**vars(args))
>   File "C:\Python27\lib\site-packages\nfldb\update.py", line 535, in run
>     doit()
>   File "C:\Python27\lib\site-packages\nfldb\update.py", line 525, in doit
>     update_games(db, batch_size=batch_size)
>   File "C:\Python27\lib\site-packages\nfldb\update.py", line 397, in update_games
>     bulk_insert_game_data(cursor, scheduled, batch_size=batch_size)
>   File "C:\Python27\lib\site-packages\nfldb\update.py", line 197, in bulk_insert_game_data
>     g = game_from_id(cursor, gsis_id)
>   File "C:\Python27\lib\site-packages\nfldb\update.py", line 54, in game_from_id
>     schedule = nflgame.sched.games[gsis_id]
> KeyError: '2017083158'

I've uninstalled nfldb/nflgame and reinstalled but the same issue occurs. I can't find that game id in the schedule.json, tho it does appear in the game table.

Furthermore, when I run the update script on my local PC, connecting to that same Postgres instance, it works fine.

Any one see this before or know the issue?

Thanks!

**Comment by etsweeney** [comment]
Well it looks like the schedule.json and players.json need to be downloaded and updated in nflgame. Figured that out from seeing this commit in the nflgame repo:
https://github.com/BurntSushi/nflgame/commit/538f52447e0f0ac3eef2bfc058ac56a06c25952f

Disregard, thanks.
