### ISSUE TITLE
Not updating?

### ISSUE THREAD

**Issue by gphett** [BurntSushi/nfldb#293]
STARTING NFLDB UPDATE AT 2017-12-03 08:17:32.793000
Connecting to nfldb... done.
Setting timezone to UTC... done.
Updating player JSON database... (last update was 2016-09-07 20:33:21.124086+00:00)
Loading games for REG 2017 week 13
Finding (profile id -> gsis id) mapping for players...
15/15 complete. (100.00%)
Done!
Downloading team rosters...
32/32 complete. (100.00%)
Done!
Fetching GSIS identifiers for players not in nflgame...
447/447 complete. (100.00%)
Done!

There were some errors during the download. Usually this is a
result of an HTTP request timing out, which means the
resulting "players.json" file is probably missing some data.
An appropriate solution is to re-run the script until there
are no more errors (or when the errors are problems on
NFL.com side.)
-------------------------------------------------------------------------------
Could not get profile URL for (00-0033928, J.Lewis)
-------------------------------------------------------------------------------
Could not get profile URL for (00-0033591, N.Brown)
-------------------------------------------------------------------------------
Could not get profile URL for (00-0033052, J.Smith)
-------------------------------------------------------------------------------
Could not get profile URL for (00-0033579, X.Woods)
-------------------------------------------------------------------------------
Could not get profile URL for (00-0032584, N.Rose)
-------------------------------------------------------------------------------
Could not get profile URL for (00-0033562, R.Switzer)
-------------------------------------------------------------------------------
Could not get profile URL for (00-0032964, B.Marshall)
-------------------------------------------------------------------------------
Could not get profile URL for (00-0032781, M.Ioannidis)
-------------------------------------------------------------------------------
Could not get profile URL for (00-0033532, J.Harvey-Clemons)
-------------------------------------------------------------------------------
Could not get profile URL for (00-0033661, L.Neal)
-------------------------------------------------------------------------------
Could not get profile URL for (00-0032362, M.Harris)
-------------------------------------------------------------------------------
Could not get profile URL for (00-0033525, R.Anderson)
-------------------------------------------------------------------------------
Could not get profile URL for (00-0033526, S.Perine)
-------------------------------------------------------------------------------
Could not get profile URL for (00-0033541, T.Charlton)
-------------------------------------------------------------------------------
Could not get profile URL for (00-0033548, C.Awuzie)
-------------------------------------------------------------------------------
Could not get player info from roster row:

<tr class="odd">
<td>72</td>
<td style="text-align:left"> <a href="/player/charleslenojr./2550169/profile">Leno, Charles, Jr.</a></td>
<td>OT</td>
<td>ACT</td>
<td> 6'3"</td>
<td>306</td>
<td>10/9/1991</td>
<td>4</td>
<td>Boise State</td></tr>

Exception:

Traceback (most recent call last):
  File "C:\Users\gphet\Anaconda2\lib\site-packages\nflgame\update_players.py", line 419, in run
    roster.append(meta_from_soup_row(team, row))
  File "C:\Users\gphet\Anaconda2\lib\site-packages\nflgame\update_players.py", line 179, in meta_from_soup_row
    last_name, first_name = map(lambda s: s.strip(), name.split(','))
ValueError: too many values to unpack

done.
Locking player table...
Updating 7216 players... done.
Locking write access to tables... done.
Updating season phase, year and week... done.
Adding schedule data for 16 games... done.
Bulk inserting data for 258 games...
        Sending batch of data to database.
        Sending batch of data to database.
        Sending batch of data to database.
        Sending batch of data to database.
        Sending batch of data to database.
        Sending batch of data to database.
        Sending batch of data to database.
Traceback (most recent call last):
  File "nfldb-update", line 39, in <module>
    nfldb.update.run(**vars(args))
  File "C:\Users\gphet\Anaconda2\lib\site-packages\nfldb\update.py", line 535, in run
    doit()
  File "C:\Users\gphet\Anaconda2\lib\site-packages\nfldb\update.py", line 525, in doit
    update_games(db, batch_size=batch_size)
  File "C:\Users\gphet\Anaconda2\lib\site-packages\nfldb\update.py", line 397, in update_games
    bulk_insert_game_data(cursor, scheduled, batch_size=batch_size)
  File "C:\Users\gphet\Anaconda2\lib\site-packages\nfldb\update.py", line 195, in bulk_insert_game_data
    do()
  File "C:\Users\gphet\Anaconda2\lib\site-packages\nfldb\update.py", line 188, in do
    nfldb.db._big_insert(cursor, table, bulk[table])
  File "C:\Users\gphet\Anaconda2\lib\site-packages\nfldb\db.py", line 356, in _big_insert
    % (table, insert_fields, values))
  File "C:\Users\gphet\Anaconda2\lib\site-packages\psycopg2\extras.py", line 249, in execute
    return super(RealDictCursor, self).execute(query, vars)
psycopg2.IntegrityError: insert or update on table "play" violates foreign key constraint "play_pos_team_fkey"
DETAIL:  Key (pos_team)=(JAX) is not present in table "team".

**Comment by kevin2107** [comment]
this has been solved on a previous issue, you need to relabel the JAX database to match the rest of the databas
