### ISSUE TITLE
NFL db update on Anaconda help

### ISSUE THREAD

**Issue by hardyaf** [BurntSushi/nfldb#321]
Hi all. I'm not sure if this is an issue, or if I just messed something up. I have successfully gotten the nflbd-update to run in the past with just a python 2.7 install, but I have since moved everything over to an Anaconda install (for a variety of reasons).

Now, I can't get the update script to run, however I can run an execute other scripts, such as the example ones in the install guide. When I try to run the update-nfldb script, this is the error I get:

(Python 2.7) C:\Users\afhar\Anaconda3\Scripts>python nfldb-update
Traceback (most recent call last):
  File "nfldb-update", line 5, in <module>
    import nfldb.update
  File "C:\Users\afhar\Anaconda3\envs\Python 2.7\lib\site-packages\nfldb\update.py", line 15, in <module>
    import nflgame
  File "C:\Users\afhar\Anaconda3\envs\Python 2.7\lib\site-packages\nflgame\__init__.py", line 97, in <module>
    import nflgame.game  # noqa
  File "C:\Users\afhar\Anaconda3\envs\Python 2.7\lib\site-packages\nflgame\game.py", line 12, in <module>
    import nflgame.sched
  File "C:\Users\afhar\Anaconda3\envs\Python 2.7\lib\site-packages\nflgame\sched.py", line 47, in <module>
    games, last_updated = _create_schedule()
  File "C:\Users\afhar\Anaconda3\envs\Python 2.7\lib\site-packages\nflgame\sched.py", line 40, in _create_schedule
    year, week = nflgame.live.current_year_and_week()
  File "C:\Users\afhar\Anaconda3\envs\Python 2.7\lib\site-packages\nflgame\live.py", line 115, in current_year_and_week
    _update_week_number()
  File "C:\Users\afhar\Anaconda3\envs\Python 2.7\lib\site-packages\nflgame\live.py", line 358, in _update_week_number
    dom = xml.parse(urllib2.urlopen(_CUR_SCHEDULE, timeout=5))
  File "C:\Users\afhar\Anaconda3\envs\Python 2.7\lib\xml\dom\minidom.py", line 1918, in parse
    return expatbuilder.parse(file)
  File "C:\Users\afhar\Anaconda3\envs\Python 2.7\lib\xml\dom\expatbuilder.py", line 928, in parse
    result = builder.parseFile(file)
  File "C:\Users\afhar\Anaconda3\envs\Python 2.7\lib\xml\dom\expatbuilder.py", line 207, in parseFile
    parser.Parse(buffer,0)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 12, column 38

Can someone help shed some light as to what I need to do to move past this?

**Comment by CPAllen55** [comment]
I'm having this same exact issue. Were you able to solve this? I did see someone mention switching out the url in live.py. That did seem to help a bit, but still seeing plenty of results like this.
