### ISSUE TITLE
Odoo v14 error 

### ISSUE THREAD

**Issue by Henrijo** [BurntSushi/nfldb#323]
Hi Folks 
 I got this error on odoo v14
Erreur:
Odoo Server Error

Traceback (most recent call last):
  File "C:\Program Files\Odoo 14\server\odoo\addons\base\models\ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "C:\Program Files\Odoo 14\server\odoo\http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "C:\Program Files\Odoo 14\server\odoo\http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files\Odoo 14\server\odoo\service\model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files\Odoo 14\server\odoo\http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files\Odoo 14\server\odoo\http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files\Odoo 14\server\odoo\http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "C:\Program Files\Odoo 14\server\odoo\addons\web\controllers\main.py", line 1389, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "C:\Program Files\Odoo 14\server\odoo\addons\web\controllers\main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files\Odoo 14\server\odoo\api.py", line 473, in __getitem__
    return self.registry[model_name]._browse(self, (), ())
  File "C:\Program Files\Odoo 14\server\odoo\modules\registry.py", line 177, in __getitem__
    return self.models[model_name]
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\Odoo 14\server\odoo\http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Program Files\Odoo 14\server\odoo\http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
KeyError: 'google.drive.config'

**Comment by BurntSushi** [comment]
I think you're on the wrong issue tracker.

**Comment by Henrijo** [comment]
how please tell me
