### ISSUE TITLE
NFLDB-Update not updating rosters

### ISSUE THREAD

**Issue by iliketowel** [BurntSushi/nfldb#47]
```
>>> C:\Python27\Scripts>python nfldb-update
-------------------------------------------------------------------------------
STARTING NFLDB UPDATE AT 2014-08-16 09:25:50.151000
Connecting to nfldb... done.
Setting timezone to UTC... done.
Updating player JSON database... (last update was 2014-08-13 00:07:18.078000+00:
00)
Loading games for PRE 2014 week 2
Downloading team rosters...
1/32 complete. (3.12%)Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\lib\site-packages\nflgame\update_players.py", line 479, in <
module>
    run()
  File "C:\Python27\lib\site-packages\nflgame\update_players.py", line 403, in r
un
    roster.append(meta_from_soup_row(team, row))
  File "C:\Python27\lib\site-packages\nflgame\update_players.py", line 161, in m
eta_from_soup_row
    profile_url = 'http://www.nfl.com%s' % tds[1].a['href']
IndexError: list index out of range
`C:\Python27\python.exe -m nflgame.update_players --no-block` failed (exit statu
s 1)
done.
Locking player table...
Updating 5946 players... done.
Locking write access to tables... done.
Updating season phase, year and week... done.
Bulk inserting data for 5 games...
        Sending batch of data to database.
```

For some reason, the rosters aren't updating (it says 1/32 complete) and   there are some other errors. I'm not sure what is causing this.

**Comment by kennysushi** [comment]
> "If it still doesn't work, could you please upgrade nflgame with pip install --upgrade nflgame and try it again? If it fails, please post the output message. There should be more details now."

Having an issue when updating nfldb for the 2016 season week 1. I was able to correctly run nfldb-update, but it didn't actually change the database to include 2016 week 1 data. I upgraded nflgame as you suggested and after retrying nfldb-update I got a much more robust looking update!:

> C:\Users\...\AppData\Local\Continuum\Anaconda2\Scripts>python nfldb-update
> -------------------------------------------------------------------------------
> STARTING NFLDB UPDATE AT 2016-09-14 11:27:41.507000
> Connecting to nfldb... done.
> Setting timezone to UTC... done.
> Locking write access to tables... done.
> Updating season phase, year and week... done.
> Adding schedule data for 321 games... done.
> Bulk inserting data for 81 games...
>         Sending batch of data to database.
>         Sending batch of data to database.

that being said... still no update when running a query. The below returns empty. Any additional suggestions? Is it a problem I run python through spyder/anaconda stack?

```
import nfldb
import pandas as pd
db = nfldb.connect()
q = nfldb.Query(db)
q.game(season_year= 2016, season_type='Regular')
for g in q.as_games():
    print(g)

[empty]
```

**Comment by ochawkeye** [comment]
Try updating your `nfldb` install and see if that helps anything.

`pip install --upgrade nfldb`

**Comment by kennysushi** [comment]
thanks for the speedy reply! this solved my issue:

`pip install --upgrade nfldb`
