### ISSUE TITLE
Unable to run nfldb-update

### ISSUE THREAD

**Issue by pherp** [BurntSushi/nfldb#88]
Hi,

Great project.  I've been able to install and load the nfldb database based on the .zip file but I am not able to run either the test top-ten-qbs.py file or the nfldb-update script.  

I'm running Windows 8.1 64-bit and am wondering if that is the issue.  

When I run nfldb-update, i get the following error:
C:\Python27>Scripts\nfldb-update
'Scripts\nfldb-update' is not recognized as an internal or external command,
operable program or batch file.

When I run the top-ten-qbs.py file, I get the following error:

C:\Python27>share\nfldb\toptenqbs.py
Traceback (most recent call last):
  File "C:\Python27\share\nfldb\toptenqbs.py", line 1, in <module>
    import nfldb
  File "C:\Python27\lib\site-packages\nfldb\__init__.py", line 61, in <module>
    from nfldb.db import __pdoc__ as __db_pdoc__
  File "C:\Python27\lib\site-packages\nfldb\db.py", line 9, in <module>
    import psycopg2
  File "C:\Python27\lib\site-packages\psycopg2\__init__.py", line 50, in <module
>
    from psycopg2._psycopg import BINARY, NUMBER, STRING, DATETIME, ROWID
ImportError: DLL load failed: The specified module could not be found.

Any thoughts?

**Comment by ochawkeye** [comment]
> C:\Python27>Scripts\nfldb-update

Try `python scripts\nfdb-update` from that location.  Despite the python path being included in the shebang line, I think Windows just won't attempt to hunt down the executable for a file without a file extension.
![image](https://cloud.githubusercontent.com/assets/2996205/8643018/670d60e6-28f3-11e5-9824-f53531d1809c.png)

> C:\Python27>share\nfldb\toptenqbs.py
As for that one, I know I had trouble installing `psycopg` in the Windows world.  Did you follow [this](https://github.com/BurntSushi/nfldb/wiki/Windows-Install) guide for installation and you obtained `psycopg` from [here](http://www.lfd.uci.edu/~gohlke/pythonlibs/#psycopg)?

**Comment by hardyaf** [comment]
Hi, I am pretty proficient in MySQL, and am assuming the query GUI for postgre will be an easy transfer for me, but I am completely new to Python. I am also having the issue from above. I believe my issue is psycopg is not installed. I googled how to install the .whl from your link (I am on windows 10) and it said I need to use easy_setup.  However, when I try to install easy_setup, I get another error message. Any chance someone here who doesn't suck at Python can help?

![easy_setup_error](https://cloud.githubusercontent.com/assets/14813879/10063277/e0d7f2c2-6239-11e5-9be0-aa0fa03a3dab.png)

Otherwise I found the two guides, especially the Windows one very helpful. This has been excellent work and I very much appreciate everything you went through writing this up. This is easily one of the best 5 things I have found on the internet, and even if I can't get the sync to work, manually copying you sql files and importing takes ~5 minutes, and opened up so much analysis options.

**Comment by ochawkeye** [comment]
Back when I wrote that Windows install tutorial, the link to [psycopg](http://www.lfd.uci.edu/~gohlke/pythonlibs/#psycopg) went to a .exe.  All binaries that are hosted over there have converted to these .whl files that might be a little bit less intuitive for a beginner, but are still pretty easy to install.

All you have to do is  `pip install X:\path\to\your\psycopg2-2.#.#-cp##-none-ARCH.whl` replacing the path and file name with your version.

As for easy_install, if you've got `pip` working properly you probably won't have much need for it, but you already have it as it is part of the standard library (you should see `easy_install.exe` in your X:\Python27\scripts folder).  If you didn't already have pip, you would use easy_install to install pip with `easy_install.exe pip`.  *Then* you could install the .whl with pip.  But since you already have pip working, you don't need to worry about that part at the moment.

**Comment by sjr1616** [comment]
I am having the exact same issue as the original post and I can't seem to figure out what the problem is. I have followed the guides, as well as the comments in this post, exactly as they are written. Even went as far as re-installing Windows, but still no luck. Any help would be greatly appreciated.

**Comment by BurntSushi** [comment]
@sjr1616 Can you please post the commands you are trying and their outputs?

**Comment by ochawkeye** [comment]
Have you tried `pip` installing the .whl file that can be downloaded from [here](http://www.lfd.uci.edu/~gohlke/pythonlibs/#psycopg)?  Download `psycopg2‑2.6.1‑cp27‑none‑win32.whl` and then (assuming you have `pip` properly installed):

`pip install X:\path\to\your\psycopg2‑2.6.1‑cp27‑none‑win32.whl`

**Comment by sjr1616** [comment]
python c:\python27\share\nfldb\top-ten-qbs.py
Traceback (most recent call last):
  File "c:\python27\share\nfldb\top-ten-qbs.py", line 1, in <module>
    import nfldb
  File "C:\Python27\lib\site-packages\nfldb\__init__.py", line 61, in <module>
    from nfldb.db import __pdoc__ as __db_pdoc__
  File "C:\Python27\lib\site-packages\nfldb\db.py", line 9, in <module>
    import psycopg2
  File "C:\Python27\lib\site-packages\psycopg2\__init__.py", line 50, in <module>
    from psycopg2._psycopg import BINARY, NUMBER, STRING, DATETIME, ROWID
ImportError: DLL load failed: The specified module could not be found.

@BurntSushi This is the error I get and it also is the exact same thing when i try to run the nfldb update command. 

@ochawkeye Yes, I have done that as well.

**Comment by ochawkeye** [comment]
For anyone that has this problem in the future...

No idea what the deal is with the bizarro issue, but it may be due to a broken version 2.6.1 build posted to the link I have included above.

Until (if ever) that gets fixed, you should be able to use [this older version 2.5.4](blackandbrew.net/psycopg2-2.5.4-cp27-none-win32.whl) that fixed @sjr1616 's problem.

**Comment by hardyaf** [comment]
I never did comment back here, but I did want to mention that the older version worked perfectly for me. Thanks so much for the help and all the work you guys put into this.
