### ISSUE TITLE
ERROR: operator does not exist: gameid = integer postgres database

### ISSUE THREAD

**Issue by Christewart** [BurntSushi/nfldb#91]
[ERROR] [08/05/2015 19:15:37.033] [NflDbApiActorSystemConfig-akka.actor.default-dispatcher-5] [akka://NflDbApiActorSystemConfig/user/$a] ERROR: operator does not exist: gameid = integer
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
  Position: 2075
org.postgresql.util.PSQLException: ERROR: operator does not exist: gameid = integer
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
  Position: 2075
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2157)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1886)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:555)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:417)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:410)
	at scala.slick.jdbc.StatementInvoker.results(StatementInvoker.scala:38)
	at scala.slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:22)
	at scala.slick.jdbc.Invoker$class.foreach(Invoker.scala:64)
	at scala.slick.jdbc.StatementInvoker.foreach(StatementInvoker.scala:16)
	at scala.slick.jdbc.Invoker$class.firstOption(Invoker.scala:29)
	at scala.slick.jdbc.StatementInvoker.firstOption(StatementInvoker.scala:16)
	at com.suredbits.core.db.CRUDActorComponent$CRUDActor$$anonfun$read$1.apply(CRUDActor.scala:31)
	at com.suredbits.core.db.CRUDActorComponent$CRUDActor$$anonfun$read$1.apply(CRUDActor.scala:30)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withSession(DatabaseComponent.scala:34)
	at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$4.withSession(JdbcBackend.scala:61)
	at com.suredbits.core.db.CRUDActorComponent$CRUDActor$class.read(CRUDActor.scala:30)
	at com.github.nfldb.models.PlayPlayerDAOComponent$PlayPlayerDAO.read(PlayPlayerDAO.scala:15)
	at com.github.nfldb.models.PlayPlayerDAOComponent$PlayPlayerDAO$$anonfun$receive$1.applyOrElse(PlayPlayerDAO.scala:19)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
	at com.github.nfldb.models.PlayPlayerDAOComponent$PlayPlayerDAO.aroundReceive(PlayPlayerDAO.scala:15)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254)
	at akka.dispatch.Mailbox.run(Mailbox.scala:221)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

I'm getting this error when I'm trying to pull information for the table play_player table. Any clues on what can be causing this, it seems like the relevant part is 

ERROR: operator does not exist: gameid = integer

**Comment by BurntSushi** [comment]
> I'm getting this error when I'm trying to pull information for the table play_player table. Any clues on what can be causing this, it seems like the relevant part is

Can you please provide enough details so that I can reproduce the problem? If you're running a query, for example, then you should show it here.

My guess is that PostgreSQL is telling you exactly how to fix the problem: you need to add a type cast somewhere in your query. I can help you figure out how to do that, but I need to see your query.

**Comment by Christewart** [comment]
0:07:11.576 TKD [NflDbApiActorSystemConfig-akka.actor.default-dispatcher-3] DEBUG s.slick.jdbc.JdbcBackend.statement - Preparing statement: select x2."gsis_id", x2."drive_id", x2."play_id", x2."player_id", x2."team", x2."fumbles_forced", x2."fumbles_lost", x2."fumbles_notforced", x2."fumbles_oob", x2."fumbles_rec", x2."fumbles_rec_tds", x2."fumbles_rec_yds", x2."fumbles_tot", x2."defense_ast", x2."defense_ffum", x2."defense_fgblk", x2."defense_frec", x2."defense_frec_tds", x2."defense_frec_yds", x2."defense_int", x2."defense_int_tds", x2."defense_int_yds", x2."defense_misc_tds", x2."defense_misc_yds", x2."defense_pass_def", x2."defense_puntblk", x2."defense_qbhit", x2."defense_safe", x2."passing_sk", x2."passing_sk_yds", x2."defense_tkl", x2."defense_tkl_loss", x2."defense_tkl_loss_yds", x2."defense_tkl_primary", x2."defense_xpblk", x2."kicking_all_yds", x2."kicking_downed", x2."kicking_fga", x2."kicking_fgb", x2."kicking_fgm", x2."kicking_fgm_yds", x2."kicking_fgmissed", x2."kicking_fgmissed_yds", x2."kicking_i20", x2."kicking_rec", x2."kicking_rec_tds", x2."kicking_tot", x2."kicking_touchback", x2."kicking_xpa", x2."kicking_xpb", x2."kicking_xpmade", x2."kicking_xpmissed", x2."passing_yds", x2."kickret_fair", x2."kickret_oob", x2."kickret_ret", x2."kickret_tds", x2."kickret_touchback", x2."kickret_yds", x2."punting_blk", x2."punting_i20", x2."punting_tot", x2."punting_touchback", x2."punting_yds", x2."puntret_downed", x2."puntret_fair", x2."puntret_oob", x2."puntret_tds", x2."puntret_tot", x2."puntret_touchback", x2."puntret_yds", x2."passing_att", x2."passing_cmp", x2."passing_cmp_air_yds", x2."passing_incmp", x2."passing_incmp_air_yds", x2."defense_int", x2."passing_sk", x2."passing_sk_yds", x2."passing_tds", x2."passing_twopta", x2."passing_twoptm", x2."passing_twoptmissed", x2."passing_yds", x2."receiving_rec", x2."receiving_tar", x2."receiving_tds", x2."receiving_twopta", x2."receiving_twoptm", x2."receiving_twoptmissed", x2."receiving_yac_yds", x2."receiving_yds", x2."rushing_att", x2."rushing_loss", x2."rushing_loss_yds", x2."passing_tds", x2."passing_twopta", x2."passing_twoptm", x2."passing_twoptmissed", x2."rushing_yds" from "play_player" x2 where (((x2."gsis_id" = 2009080950) and (x2."drive_id" = 1)) and (x2."play_id" = 152)) and (x2."player_id" = '00-0021970')

**Comment by BurntSushi** [comment]
A smaller test case is easier to debug:

```
nfldb=# select home_team, away_team from game where gsis_id = 2009080950;
ERROR:  operator does not exist: gameid = integer
LINE 1: ...lect home_team, away_team from game where gsis_id = 20090809...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
```

The problem is that `gsis_id` is a string, not an integer. So you need quotes:

```
nfldb=# select home_team, away_team from game where gsis_id = '2009080950';
 home_team | away_team 
-----------+-----------
 TEN       | BUF
(1 row)
```

You can see the types of all fields in a table with the `\d` command:

```
nfldb=# \d game
                Table "public.game"
     Column     |         Type         | Modifiers 
----------------+----------------------+-----------
 gsis_id        | gameid               | not null
 gamekey        | character varying(5) | 
 start_time     | utctime              | not null
 week           | usmallint            | not null
 day_of_week    | game_day             | not null
 season_year    | usmallint            | not null
 season_type    | season_phase         | not null
 finished       | boolean              | not null
 home_team      | character varying(3) | not null
 home_score     | usmallint            | not null
 home_score_q1  | usmallint            | 
 home_score_q2  | usmallint            | 
 home_score_q3  | usmallint            | 
 home_score_q4  | usmallint            | 
 home_score_q5  | usmallint            | 
 home_turnovers | usmallint            | not null
 away_team      | character varying(3) | not null
 away_score     | usmallint            | not null
 away_score_q1  | usmallint            | 
 away_score_q2  | usmallint            | 
 away_score_q3  | usmallint            | 
 away_score_q4  | usmallint            | 
 away_score_q5  | usmallint            | 
 away_turnovers | usmallint            | not null
 time_inserted  | utctime              | not null
 time_updated   | utctime              | not null
```

All of this was done in the `psql` read-eval-print-loop (REPL).

**Comment by BurntSushi** [comment]
To view all types, you can run `\dT+` or `\dT+ gameid` for a specific type. Or you can look at the code that creates the DB schema: https://github.com/BurntSushi/nfldb/blob/master/nfldb/db.py#L473-L476

**Comment by Christewart** [comment]
This was exactly what the problem was, you can close this issue. Thank you!
